#cloud-config
# network-verifier-required-variables=TIMEOUT,DELAY,URLS
${CACERT_RENDERED}
runcmd:
  - systemctl mask --now serial-getty@ttyS0.service
  - dmesg -D
  - echo "${USERDATA_BEGIN}" >/dev/ttyS0
  - export http_proxy=${HTTP_PROXY} https_proxy=${HTTPS_PROXY}
  - curl --retry 3 --retry-connrefused -t B -Z -s -I -m ${TIMEOUT} -w "%{stderr}${LINE_PREFIX}%{json}\n" ${CURLOPT} ${URLS} --proto =http,https,telnet ${TLSDISABLED_URLS_RENDERED} 2>/dev/ttyS0
  - echo "${USERDATA_END}" >/dev/ttyS0
power_state:
  delay: ${DELAY}
  mode: poweroff
  message: Auto-terminating instance due to timeout
  timeout: 300
